# Generated by Django 5.0.6 on 2024-06-30 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_remove_feesstructure_lab_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfees',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.courses'),
        ),
    ]
