# Generated by Django 4.2.4 on 2025-02-15 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0005_alter_studentfees_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentfees",
            name="course",
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_face_registered",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("1", "HOD"), ("2", "Staff"), ("3", "Student")],
                default="1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="studentfees",
            name="total_fees",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.courses",
            ),
        ),
        migrations.CreateModel(
            name="FaceEncoding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("encoding", models.BinaryField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
