# Generated by Django 4.2.4 on 2025-02-16 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "student_management_app",
            "0007_courses_created_by_feesstructure_created_by_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentfees",
            name="total_fees",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
