# Generated by Django 4.2.4 on 2025-02-16 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0008_alter_studentfees_total_fees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="students",
            name="created_by",
        ),
    ]
