# Generated by Django 4.2.4 on 2025-03-22 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("student_management_app", "0009_remove_students_created_by"),
    ]

    operations = [
        migrations.CreateModel(
            name="BunkDetection",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="bunk_images/")),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.staffs",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_management_app.students",
                    ),
                ),
            ],
        ),
    ]
